version: "3.7"

services:
  devas-mysql:
    image: mysql:8.3
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - '../../devas-volumes/mysql:/var/lib/mysql'
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: Yumiko1@
      MYSQL_DATABASE: devas
      MYSQL_USER: Yumiko
      MYSQL_PASSWORD: Yumiko1@
    networks:
      - default
